---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envs
data:
  X_AAA: aaa
  X_BBB: bbb
  X_CCC: ccc
  COMMIT_HASH: '{{ .Values.commit_sha | trunc 7 }}'
  ARGOCD_APP_NAME: '{{ .Values.ARGOCD_APP_NAME }}'
  ARGOCD_APP_NAMESPACE: '{{ .Values.ARGOCD_APP_NAMESPACE }}'
  ARGOCD_APP_REVISION: '{{ .Values.ARGOCD_APP_REVISION }}'
  ARGOCD_APP_REVISION_SHORT: '{{ .Values.ARGOCD_APP_REVISION_SHORT }}'
  ARGOCD_APP_REVISION_X: '{{ .Values.ARGOCD_APP_REVISION_X }}'
  ARGOCD_APP_SOURCE_PATH: '{{ .Values.ARGOCD_APP_SOURCE_PATH }}'
  ARGOCD_APP_SOURCE_REPO_URL: '{{ .Values.ARGOCD_APP_SOURCE_REPO_URL }}'
  ARGOCD_APP_SOURCE_TARGET_REVISION: '{{ .Values.ARGOCD_APP_SOURCE_TARGET_REVISION }}'
