---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf.template: |
    server_tokens off;
    tcp_nopush on;
    tcp_nodelay on;

    fastcgi_connect_timeout 30s;
    fastcgi_read_timeout 30s;
    fastcgi_send_timeout 30s;

    server {
        listen 80;
        server_name localhost;

        error_page 500 502 503 504  /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }

        location = /favicon.ico {
            access_log off;
            empty_gif;
            expires 30d;
        }

        location / {
            fastcgi_pass  ${FASCGI_HOST};
            include	      fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
        }
    }
