---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-index
data:
  index.php: |
    <?php
    header('Content-Type: application/json');
    echo json_encode($_SERVER, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . PHP_EOL;
