---

helm:
  parameters:
  - { name: ARGOCD_APP_NAME,                   value: $ARGOCD_APP_NAME }
  - { name: ARGOCD_APP_NAMESPACE,              value: $ARGOCD_APP_NAMESPACE }
  - { name: ARGOCD_APP_REVISION,               value: $ARGOCD_APP_REVISION }
  - { name: ARGOCD_APP_REVISION_SHORT,         value: $ARGOCD_APP_REVISION_SHORT }
  - { name: ARGOCD_APP_SOURCE_PATH,            value: $ARGOCD_APP_SOURCE_PATH }
  - { name: ARGOCD_APP_SOURCE_REPO_URL,        value: $ARGOCD_APP_SOURCE_REPO_URL }
  - { name: ARGOCD_APP_SOURCE_TARGET_REVISION, value: $ARGOCD_APP_SOURCE_TARGET_REVISION }
  valueFiles:
    - values.yaml
    - values-ovedrride.yaml
