---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd-hooks
spec:
  project: default
  source:
    repoURL: https://github.com/ngyuki-sandbox/argocd-example.git
    targetRevision: main
    path: apps/argocd-hooks/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-hooks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
