---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: myapp
spec:
  project: default
  source:
    repoURL: https://github.com/ngyuki-sandbox/argocd-example.git
    targetRevision: main
    path: apps/myapp/
    helm:
      valueFiles:
        - values.yaml
        - values.dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
