---
apiVersion: v1
kind: ConfigMap
metadata:
  name: script
data:
  script.sh: |
    #!/bin/sh
    curl -s -X POST "$SLACK_INCOMING_URL" \
      -H content-type:application/json --data "{
        \"username\": \"ArgoCD\",
        \"icon_url\" : \"https://argo-cd.readthedocs.io/en/stable/assets/logo.png\",
        \"attachments\": [{
          \"color\": \"#cccccc\",
          \"text\": \"$MESSAGE\"
        }]
      }"
